### ISSUE TITLE
Cached emojis don't show up after running !emojis

### ISSUE THREAD

**Issue by SwiftWinds** [architus/architus#139]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/12981958/119540325-2ddecf00-bd42-11eb-890b-6c561f2f131a.png">

Let me know what I can do to provide more debugging info, and I will be more than happy to provide them!

**Comment by SwiftWinds** [comment]
Also, there are definitely cached emojis; the server has surpassed 50 emojis by quite a bit.

**Comment by johnyburd** [comment]
Can you send me your [server id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) -  johnyburd#1022

**Comment by johnyburd** [comment]
I believe I've fixed the issue. Please let me know if you experience any further problems.
