### ISSUE TITLE
All emojis disappeared

### ISSUE THREAD

**Issue by SwiftWinds** [architus/architus#145]
Suddenly Architus deleted all emojis from my server:

![image](https://user-images.githubusercontent.com/12981958/131268631-fb73c99b-99da-4ecd-9ae0-fdd33a6b8470.png)

and put them in cache: https://cdn.archit.us/assets/878159977922301966.png

If I type any emoji in chat (e.g., :ksoo:), Architus neither replaces the string with an emoji nor takes the emoji from cache back into the server (even though it is in cache). How can I get my emojis back?

Thanks for the help!

**Comment by johnyburd** [comment]
Can you dm me your server's id on discord johnyburd#1022

**Comment by SwiftWinds** [comment]
Sent you a friend request. Thanks for the help! :)

**Comment by SwiftWinds** [comment]
Thanks for helping resolve this issue! I'll close it now. :)
