### ISSUE TITLE
youtube-dl needs to be updated frequently and randomly

### ISSUE THREAD

**Issue by johnyburd** [architus/architus#54]
Our music service relies on a program called youtube-dl to download videos from youtube.  It's not supported by google, so youtube regularly breaks it and then youtube-dl updates to fix.  We need to update youtube-dl regularly in order to stay on top of these changes.

* Find the best solution for a scheduled task in docker (maybe cron idk)
* Schedule `python3 -m pip install youtube-dl --upgrade` to run every hour

**Comment by jammiess** [comment]
Solved in the cron branch.

**Comment by johnyburd** [comment]
My got flow :rage:
